GSEM/GSEventManager/GSEventManager/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from GSEventManager import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eventmanager.urls')),
    path('', include('accounts.urls')),
	path('', include('publicationmanager.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GSEM/GSEventManager/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

GSEM/GSEventManager/eventmanager/urls.py
from django.urls import path
from django.contrib.auth import authenticate
from . import views

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('eventmanager/<int:pk>/', views.event_detail, name='event_detail'),
    path('eventmanager/new', views.event_new, name='event_new'),
    path('eventmanager/<int:pk>/edit', views.event_edit, name='event_edit'),
    path('eventmanager/search', views.event_search, name='event_search'),
    path('eventmanager/<int:pk>/attend_event/', views.attend_event, name='attend_event'),
    path('eventmanager/<int:pk>/comment', views.add_comment, name='add_comment'),
    path('eventmanager/<int:pk>/spam_redirect', views.add_comment, name='add_comment')
    # path('eventmanager/login/', views.login, name='login'),
]

GSEM/GSEventManager/publicationmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'publicationmanager'
urlpatterns = [
	path('request_email', views.request_email, name='request_email'),
	path('confirm_email', views.confirm_email, name='confirm_email'),
]

GSEM/GSEventManager/eventmanager/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.


class Event(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    event_name = models.CharField(max_length=200)
    image = models.ImageField(blank=True, null=True)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    event_date = models.DateTimeField(default=timezone.now)
    event_place = models.CharField(max_length=200)
    

    def post(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.event_name


class Comment(models.Model):
    event = models.ForeignKey('eventmanager.Event', on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.content


class Attendee(models.Model):
    # event = models.ForeignKey('Event', on_delete=models.CASCADE)
    event_name = models.CharField(max_length=200)
    # user_name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    user_email = models.CharField(max_length=200)
    user_name = models.CharField(max_length=200)

    def attend(self):
        self.save()

GSEM/GSEventManager/eventmanager/forms.py
from django import forms
from .models import Event, Comment


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'text', 'event_date', 'event_place', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

GSEM/GSEventManager/eventmanager/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Event, Comment, Attendee
from .forms import EventForm, CommentForm
from django.shortcuts import redirect

import re
import pickle
import numpy as np

# Create your views here.
def event_list(request):
    events = Event.objects.order_by('-created_date')
    return render(request, 'eventmanager/event_list.html', {'events': events})

def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    form = CommentForm()
    user = request.user.username
    attendees = Attendee.objects.filter(user_name=user)
    attending = False
    for attendee in attendees:
        if attendee.event_name == event.event_name:
            attending = True
        else:
            attending = False
    return render(request, 'eventmanager/event_detail.html', {'event': event, 'attending': attending, 'form': form})

def event_new(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.published_date = timezone.now()
            event.save()
            return redirect('event_detail', pk=event.pk)
    else:
        form = EventForm()
    return render(request, 'eventmanager/event_edit.html', {'form': form})

def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        form = EventForm(request.POST,request.FILES or None, instance=event, )
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.published_date = timezone.now()
            event.save()
            return redirect('event_detail', pk=event.pk)
    else:
        form = EventForm(instance=event)
    return render(request, 'eventmanager/event_edit.html', {'form': form})
import re

def event_search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        events = Event.objects.filter(event_name__icontains=q).order_by('-created_date')
        events.union(Event.objects.filter(text__icontains=q))
        # events = Event.objects.get(Q(event_name__icontains=q) | Q(text__icontains=q)).order_by('-created_date')
        return render(request, 'eventmanager/event_search.html', {'events': events, 'query': q})
    else:
        return redirect('event_list')

def censor(words):
    black_list = ["fuck", "shit", "piss", "damn", "ass", "cock", "balls", "nigger"] #Add words to censor here
    text = words
    patt = re.compile("|".join(black_list), re.I)
    return patt.sub(lambda m: "*" * len(m.group(0)) , text)

def check_spam(words): #1 = spam, 0 = not spam
    stopset = pickle.load(open("/home/gsem/gsem.pythonanywhere.com/GSEM/GSEventManager/eventmanager/spamStopset.pkl", 'rb'))
    classifier = pickle.load(open("/home/gsem/gsem.pythonanywhere.com/GSEM/GSEventManager/eventmanager/spamPickle.pkl", 'rb'))
    vectorizer = pickle.load(open("/home/gsem/gsem.pythonanywhere.com/GSEM/GSEventManager/eventmanager/spamVectorizer.pkl", 'rb'))
    prediction = classifier.predict(vectorizer.transform(np.array([words])))
    return prediction[0]
	
def add_comment(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.event = event
            comment.user = request.user
            if check_spam(request.POST.get('content')) == 0:
                comment.content = censor(request.POST.get('content'))
            else:
                return render(request, 'eventmanager/spam_redirect.html') #redirects here if it is spam
            comment.save()
            return redirect('event_detail', pk=event.pk)
    else:
        form = CommentForm()
    return render(request, 'eventmanager/add_comment.html', {'form': form})


def attend_event(request, pk):
    if request.method == "GET":
        attendee = Attendee()
        event = get_object_or_404(Event, pk=pk)
        user = request.user
        attendee.event_name = event.event_name
        attendee.user_name = user.username
        attendee.user_email = user.email
        attendee.save()
        return redirect('event_list')
    else:
        return redirect('event_list')
		

GSEM/GSEventManager/eventmanager/templates/eventmanager/add_comment.html
{% extends 'eventmanager/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/base.html
{% load staticfiles %}
<html>

<head>
    <title>Georgia Southern Events</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Alfa+Slab+One&subset=latin,latin-ext" rel="stylesheet" type="text/css" >

    <link rel="stylesheet" href="{% static 'css/eventmanager.css' %}">



</head>

<body>
        <div class="page-header">


            {% if user.is_authenticated %}
             <div class="top-menu"  style="font-size:22px"> Hello {{ user.username }}, &nbsp;
             <a  style="font-size:22px" href="/logout/" class="top-menu">Logout &nbsp;<span class="glyphicon glyphicon-log-out" ></span></a>
             </div>

            {% if user.is_staff %}
            <a href="{% url 'event_new' %}" class="top-menu" title="Add new Event"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <!--<a href="/logout/" class="top-menu"> Logout <span class="glyphicon glyphicon-log-out"></span></a>-->
            {% else %}
            <a href="/login/" class="top-menu"> Login <span class="glyphicon glyphicon-log-in"></span></a>
            <a href="/signup/" class="top-menu"> Sign Up <span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}

            <h1><img src="/media/thumb-eagle.PNG" style="width:70px;height:70px;"><a href="/">Georgia Southern Events</a></h1>




            <form align="right" class="select2-search__field" action="{% url 'event_search' %}" method="get">
                <input class="form-row" type="search" name="q" placeholder="Search" aria-label="Search">
                <button type="submit" value="Search"> Search </button>
            </form>

        </div>


<div class="content">
    <div class="event">

            {% block content %}
            {% endblock %}


    </div>
</div>


</body>
</html>

GSEM/GSEventManager/eventmanager/templates/eventmanager/event_detail.html
{% extends 'eventmanager/base.html' %}

{% block content %}

<script>
    function goBack() {
        window.history.back();
    }
</script>
<p align="right" class="content">
    <button class="btn btn-primary" onclick="goBack()">Go Back</button>
</p>

<div class="event">
    {% if event.event_date %}
    <div class="date">
        Event Date: {{ event.event_date }}
    </div>
    {% endif %}

    {% if user.is_authenticated and user.is_staff %}
    <a class="btn btn-primary" href="{% url 'event_edit' pk=event.pk %}"><span
            class="glyphicon glyphicon-pencil"></span></a>
    {% endif %}

    {% if user.is_authenticated %}
	
    {% if attending %}
    <h3>You are attending this event</h3>

    {% else %}
    <a class="btn btn-primary" href="{% url 'attend_event' pk=event.pk %}"><span label="Attend"
                                                                                 class="glyphicon glyphicon-road"> RSVP</span></a>
    {% endif %}
    {% endif %}


    <h1>{{ event.event_name }}</h1>
    {% if event.image %}
    <img src="{{ event.image.url }}">
    {% else %}
	<br></br>
	{% endif %}
</div>


<p><h4>{{ event.text|linebreaksbr }}</h4></p>

<!--<div id="disqus_thread"></div>-->
<!--<script>-->

<!--/**-->
<!--*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.-->
<!--*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/-->
<!--/*-->
<!--var disqus_config = function () {-->
<!--this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable-->
<!--this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable-->
<!--};-->
<!--*/-->
<!--(function() { // DON'T EDIT BELOW THIS LINE-->
<!--var d = document, s = d.createElement('script');-->
<!--s.src = 'https://gsevents.disqus.com/embed.js';-->
<!--s.setAttribute('data-timestamp', +new Date());-->
<!--(d.head || d.body).appendChild(s);-->
<!--})();-->
<!--</script>-->
<!--<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>-->


<h2> Location:</h2>
<h3>{{ event.event_place }}</h3>
<a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"> Share on Facebook |</a>

<a href="https://twitter.com/home?status=You're%20Invited!%20{{request.build_absolute_uri}}"> Share on Twitter |</a>

<a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'> Share on Google+ </a>


<form method="POST" action="{% url 'publicationmanager:request_email' %}">
    {% csrf_token %}
    <input class="btn btn-primary" type="submit" name="Submit" value="Share via. Email">
</form>

{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'add_comment' pk=event.pk %}">Add comment</a>
{% endif %}


{% for comment in event.comments.all %}
<div class="comment">
    <div class="date">{{ comment.timestamp }}</div>
    <strong>{{ comment.user }}</strong>
    <p>{{ comment.content|linebreaks }}</p>
</div>
{% empty %}
<p>No comments here yet. </p>
{% endfor %}


{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/event_edit.html
{% extends 'eventmanager/base.html' %}

{% block content %}
    <h1> New Post</h1>
    <form method="POST" class="post-form" enctype='multipart/form-data'>{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/event_list.html
{% extends 'eventmanager/base.html' %}
{% block content %}
{% load staticfiles %}

<script>
function myFunction() {
   var element = document.getElementById("myDIV");
   element.classList.toggle("flex-container");
}
</script>

<div align="right" class="content" ><a  class="btn btn-primary" onclick="myFunction()" ><span  class="glyphicon glyphicon-th-list"></span></a></div>

<div id="myDIV" class="flex-container" >
    {% for event in events %}

    <div>
        <h1><a href="{% url 'event_detail' pk=event.pk %}" title="See more!">{{ event.event_name }}</a></h1>
        <!--<p>{{ event.text|linebreaksbr }}</p>-->
        <p>{{ event.event_date }}</p>

    </div>
    {% endfor %}

</div>

<!--<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;height=225&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;ctz=America%2FNew_York" style="border-width:0" width="300" height="225" frameborder="0" scrolling="no"></iframe>-->
{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/event_search.html
{% extends 'eventmanager/base.html' %}

{% block content %}
    <h1> Search Results for "{{ query }}"</h1>
            {% for event in events %}
                <div class="event">
                    <div class="date">
                        published: {{ event.created_date }}
                    </div>
                    <h1><a href="{% url 'event_detail' pk=event.pk %}">{{ event.event_name }}</a></h1>
                </div>
            {% endfor %}
{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/login.html
{% extends "eventmanager/base.html" %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password dont match. Try again.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {%csfr_token %}
            <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            </table>

            <input type="submit" value="login" />
            <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

GSEM/GSEventManager/eventmanager/templates/eventmanager/spam_redirect.html
<h2> Please note, the commenting system is a means of giving feedback about the event or discussing the event</h2>
<br>What does this mean?</br>
<br>No soliciting</br>
<br>No spamming</br>
<br>Every so often our AI makes an oopsie, and if you beleive you fall into this category, 
please simply reword your comment. Thanks and have a wonderful day! :)</br>